export const mockErrorUserAlreadyExists = {
  statusCode: 422,
  error: "User already exists.",
};
